name: CI
on: [push, pull_request, workflow_dispatch]
jobs:
  autohotkey:
    runs-on: windows-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
      - name: Install AutoHotKey
        run: choco install autohotkey
      - name: Run tests
        env:
          PATH: C:\Program Files\AutoHotkey\autohotkey.exe
        run: autohotkey /ErrorStdOut minescript.ahk
      - name: Publish Test Report
        uses: mikepenz/action-junit-report@v3
        if: always() # always run even if the previous step fails
        with:
          report_paths: junit.xml
          check_name: AutoHotKey Test Report
          fail_on_failure: true
